"""add_payment_model

Revision ID: cb0d7e6637ed
Revises: 297add44e98d
Create Date: 2026-07-26 08:40:20.827467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb0d7e6637ed'
down_revision: Union[str, Sequence[str], None] = '297add44e98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_payment_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_stripe_session_id'), ['stripe_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_stripe_session_id'))
        batch_op.drop_index(batch_op.f('ix_payment_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_id'))

    op.drop_table('payment')
    # ### end Alembic commands ###
